### ISSUE TITLE
Throwing a Syntax Error

### ISSUE THREAD

**Issue by Honestpuck** [scriptingosx/quickpkg#8]
I'm using version 0.8.1 and have pointed the shebang to the latest version of Managed Python (`/Library/ManagedFrameworks/Python/Python3.framework/Versions/Current/bin/python3`).

I'm getting:
```
./quickpkg ~/Downloads/Notion-2.0.24.dmg
  File "/Users/tonyw/Dropbox/work/quickpkg-0.8.1/./quickpkg", line 126
    except NSPropertyListSerializationException, error:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

1.0beta throws a different error :
```
./quickpkg ~/Downloads/Notion-2.0.24.dmg
Traceback (most recent call last):
  File "/Users/tonyw/Dropbox/work/quickpkg-1.0beta/./quickpkg", line 277, in <module>
    dmgvolumepaths = attachdmg(item_path)
  File "/Users/tonyw/Dropbox/work/quickpkg-1.0beta/./quickpkg", line 88, in attachdmg
    (theplist, alltext) = getFirstPlist(info_result["stdout"])
  File "/Users/tonyw/Dropbox/work/quickpkg-1.0beta/./quickpkg", line 52, in getFirstPlist
    plist_start_index = textString.find(plist_header)
TypeError: argument should be integer or bytes-like object, not 'str'
```

**Comment by Honestpuck** [comment]
I've had this problem on two different computers now.

**Comment by scriptingosx** [comment]
Have you tried the 1.0 pre-release version? https://github.com/scriptingosx/quickpkg/releases/tag/v1.0beta

**Comment by Honestpuck** [comment]
Yes. It throws a different error that I detailed above.

**Comment by scriptingosx** [comment]
can you check this with the 1.0 release? Thank you

**Comment by Honestpuck** [comment]
Testing the 1.0 release on Apple Silicon using the latest managed Python worked perfectly.

```
❯ ./quickpkg ~/Downloads/Notion-2.1.11-arm64.dmg
Notion-2.1.11.pkg
```
